# Configuration for development

# We don't want to use the production instance of search.quarkus.io for development.
search:

# Use this to directly use the local instance of search.quarkus.io
  script-mode: "direct"
  host: "http://localhost:8080"

# Use this to copy from the local instance of search.quarkus.io
#  script_mode: "cached"


# Use this to copy from the production instance of search.quarkus.io
#  script_mode: "cached"
#  host: "https://search.quarkus.io/"
